---
title: "esavis_v1"
output: html_document
---

```{r primer chunk, include = F, warning=F}
#Dont forget to set your own working directory
setwd("C:/Users/isaac/OneDrive/Documentos/Protocolos_de_investigacion/ESAVIS/esavis_crisis_convulsivas")

library(tidyverse); library(Hmisc); library(lubridate); library(haven)

```


```{r base esavis, include = F, warning=F}

esavis <- read_sav("esavis.sav") 
names(esavis) <- tolower(names(esavis))

esavis_v1 <- esavis %>%  
  mutate(tipo_esavi=ifelse(tipo_esavi==0, "grave", "no grave"),
         vacuna=case_when(vacuna==1~"astrazeneca",
                          vacuna==2~"pfizer",
                          vacuna==3~"sinovac",
                          vacuna==4~"cansino",
                          vacuna==5~"sputnik",
                          vacuna==6~"janssen",
                          vacuna==7~"moderna"),
         sexo=ifelse(sexo==2, "mujer", "hombre"),
         covid_previo=ifelse(sars==1, T, F),
         ocupacion=case_when(ocupación==0~"se desconoce",
                             ocupación==1~"personal de salud",
                             ocupación==2~"militar",
                             ocupación==3~"maestro",
                             ocupación==4~"pensionado",
                             ocupación==5~"hogar",
                             ocupación==6~"desempleado",
                             ocupación==7~"sector salud no medico",
                             ocupación==8~"empleado",
                             ocupación==9~"estudiante",
                             ocupación==10~"licenciatura",
                             ocupación==11~"desempleado"),
         num_faes=`@#_faes`,
         edad=as.numeric(edad),
         sexo_m=ifelse(sexo=="mujer", T, F))


```


```{r table 1, include = F, warning=F}
#FUNCIONES para la tabla
categorico <- function(variable, otro=NA){
  if(is.na(otro)){
  c(str_c(sum(filter(esavis_v1, epilepsia_previa==0)[,variable]), " (", 
                                 round(sum(filter(esavis_v1, epilepsia_previa==0)[,variable])/
                                         nrow(filter(esavis_v1, epilepsia_previa==0)), 3)*100, "%)"),
                          #  
                           str_c(sum(filter(esavis_v1, epilepsia_previa==1)[,variable]), " (", 
                                 round(sum(filter(esavis_v1, epilepsia_previa==1)[,variable])/
                                         nrow(filter(esavis_v1, epilepsia_previa==1)), 3)*100, "%)"),
                           #
                           str_c(sum(esavis_v1[,variable]), " (", 
                                 round(sum(esavis_v1[,variable])/
                                         nrow(esavis_v1), 3)*100, "%)"))
  }else{
    c(str_c(sum(filter(esavis_v1, epilepsia_previa==0)[,variable]==otro), " (", 
                                 round(sum(filter(esavis_v1, epilepsia_previa==0)[,variable]==otro)/
                                         nrow(filter(esavis_v1, epilepsia_previa==0)), 3)*100, "%)"),
                          #  
                           str_c(sum(filter(esavis_v1, epilepsia_previa==1)[,variable]==otro), " (", 
                                 round(sum(filter(esavis_v1, epilepsia_previa==1)[,variable]==otro)/
                                         nrow(filter(esavis_v1, epilepsia_previa==1)), 3)*100, "%)"),
                           #
                           str_c(sum(esavis_v1[,variable]==otro), " (", 
                                 round(sum(esavis_v1[,variable]==otro)/
                                         nrow(esavis_v1), 3)*100, "%)"))
    
  }
  
}


#CONTEOS
conteo <- c(str_c(nrow(filter(esavis_v1, epilepsia_previa==0)), " (", (round(nrow(filter(esavis_v1, epilepsia_previa==0))/nrow(esavis_v1), 1))*100, "%)"), 
            str_c(nrow(filter(esavis_v1, epilepsia_previa==1)), " (", (round(nrow(filter(esavis_v1, epilepsia_previa==1))/nrow(esavis_v1), 1))*100, "%)"),
            str_c(nrow(esavis_v1), " (", (round(nrow(esavis_v1)/nrow(esavis_v1), 1))*100, "%)"))


#EDAD
edad <- c(str_c(median(filter(esavis_v1, epilepsia_previa==0)$edad), " (", fivenum(filter(esavis_v1, epilepsia_previa==0)$edad)[2],
                            "-", fivenum(filter(esavis_v1, epilepsia_previa==0)$edad)[4], ")"),
                      
                      str_c(median(filter(esavis_v1, epilepsia_previa==1)$edad), " (", fivenum(filter(esavis_v1, epilepsia_previa==1)$edad)[2],
                            "-", fivenum(filter(esavis_v1, epilepsia_previa==1)$edad)[4], ")"),
                      
                      str_c(median(esavis_v1$edad), " (", fivenum(esavis_v1$edad)[2],
                            "-", fivenum(esavis_v1$edad)[4], ")"))

#DÍAS INTERNADO
dias_internado <- c(str_c(median(filter(esavis_v1, epilepsia_previa==0)$diasinternador, na.rm = T), " (", fivenum(filter(esavis_v1, epilepsia_previa==0)$diasinternador, na.rm = T)[2],
                            "-", fivenum(filter(esavis_v1, epilepsia_previa==0)$diasinternador, na.rm = T)[4], ")"),
                      
                      str_c(median(filter(esavis_v1, epilepsia_previa==1)$diasinternador, na.rm = T), " (", fivenum(filter(esavis_v1, epilepsia_previa==1)$diasinternador, na.rm = T)[2],
                            "-", fivenum(filter(esavis_v1, epilepsia_previa==1)$diasinternador, na.rm = T)[4], ")"),
                      
                      str_c(median(esavis_v1$diasinternador, na.rm = T), " (", fivenum(esavis_v1$diasinternador, na.rm = T)[2],
                            "-", fivenum(esavis_v1$diasinternador, na.rm = T)[4], ")"))

#NUMBER OF SEIZURES
num_crisis <- c(str_c(median(filter(esavis_v1, epilepsia_previa==0)$num_de_crisis, na.rm = T), " (", fivenum(filter(esavis_v1, epilepsia_previa==0)$num_de_crisis, na.rm = T)[2],
                            "-", fivenum(filter(esavis_v1, epilepsia_previa==0)$num_de_crisis, na.rm = T)[4], ")"),
                      
                      str_c(median(filter(esavis_v1, epilepsia_previa==1)$num_de_crisis, na.rm = T), " (", fivenum(filter(esavis_v1, epilepsia_previa==1)$num_de_crisis, na.rm = T)[2],
                            "-", fivenum(filter(esavis_v1, epilepsia_previa==1)$num_de_crisis, na.rm = T)[4], ")"),
                      
                      str_c(median(esavis_v1$num_de_crisis, na.rm = T), " (", fivenum(esavis_v1$num_de_crisis, na.rm = T)[2],
                            "-", fivenum(esavis_v1$num_de_crisis, na.rm = T)[4], ")"))






table_1 <- data.frame(tipo_paciente=c("sin epilepsia previa", "epilepsia previa", "todos"),
                      conteo=conteo,
                      edad=edad,
                      sexo=categorico("sexo_m"),
                      vacuna=rep("-", times= 3),
                      astra=categorico("vacuna", "astrazeneca"),
                      cansino=categorico("vacuna", "cansino"),
                      moderna=categorico("vacuna", "moderna"),
                      pfizer=categorico("vacuna", "pfizer"),
                      sinovac=categorico("vacuna", "sinovac"),
                      sputnik=categorico("vacuna", "sputnik"),
                      covid_previo=categorico("covid_previo"),
                      tipo_crisis=rep("-", times=3),
                      generalizadas=categorico("crisis_convulsivas"),
                      no_generalizadas=categorico("crisis_convulsivas", 0),
                      NUM_CRISIS=num_crisis,
                      severidad_aefi=rep("-", times=3),
                      severidad_aefi_nograve=categorico("tipo_esavi", "no grave"),
                      severidad_aefi_grave=categorico("tipo_esavi", "grave"),
                      status=categorico("estatusepiléptico"),
                      stroke=categorico("evc"),
                      neuroinfeccion=categorico("neuroinfeccion"),
                      dias_hospitalizacion=dias_internado,
                      defuncion=categorico("defuncion"))


```


```{r incidencia de esavis, include = F, warning = F}
esavis_incidencia <- esavis_v1 %>% 
  group_by(vacuna) %>% 
  count() %>% 
  mutate(dosis_totales=case_when(vacuna=="astrazeneca"~38516372,
                                 vacuna=="cansino"~2979697,
                                 vacuna=="moderna"~2318057,
                                 vacuna=="pfizer"~16646623,
                                 vacuna=="sinovac"~14532954,
                                 vacuna=="sputnik"~5812864),
         eventos_por_millon=round((n/dosis_totales)*1000000, 2)) %>% 
  arrange(desc(eventos_por_millon))



esavis_incidencia_sin_causa <- filter(esavis_v1, evc==0&neuroinfeccion==0&primera_crisis==1) %>% 
  group_by(vacuna) %>% 
  count() %>% 
  mutate(dosis_totales=case_when(vacuna=="astrazeneca"~38516372,
                                 vacuna=="cansino"~2979697,
                                 vacuna=="moderna"~2318057,
                                 vacuna=="pfizer"~16646623,
                                 vacuna=="sinovac"~14532954,
                                 vacuna=="sputnik"~5812864),
         eventos_por_millon=round((n/dosis_totales)*1000000, 2)) %>% 
  arrange(desc(eventos_por_millon)) 


```



```{r intervalos de confianza, include = F, warning=F}


ci_vacuna <- function(x, y){
  if(y=="todos"){
  round(binconf(filter(esavis_incidencia, vacuna==x)$n, n=filter(esavis_incidencia, vacuna==x)$dosis_totales , alpha=0.05,
        method="wilson",
        include.x=FALSE, include.n=FALSE, return.df=FALSE)*1000000, 2)
  }else{
    round(binconf(filter(esavis_incidencia_sin_causa, vacuna==x)$n, n=filter(esavis_incidencia_sin_causa, vacuna==x)$dosis_totales , alpha=0.05,
        method="wilson",
        include.x=FALSE, include.n=FALSE, return.df=FALSE)*1000000, 2)
  }
}

#INTERVALOS DE CONFIANZA PARA TODOS LOS EVENTOS

table_2 <- data.frame(moderna=c(str_c(ci_vacuna("moderna", y="todos")[1], " (", ci_vacuna("moderna", y="todos")[2], "-", ci_vacuna("moderna", y="todos")[3], ")"),
                                str_c(ci_vacuna("moderna", y="sin_otra_explicacion")[1], " (", ci_vacuna("moderna", y="sin_otra_explicacion")[2], "-", ci_vacuna("moderna", y="sin_otra_explicacion")[3], ")")),
                      pfizer=c(str_c(ci_vacuna("pfizer", y="todos")[1], " (", ci_vacuna("pfizer", y="todos")[2], "-", ci_vacuna("pfizer", y="todos")[3], ")"),
                                str_c(ci_vacuna("pfizer", y="sin_otra_explicacion")[1], " (", ci_vacuna("pfizer", y="sin_otra_explicacion")[2], "-", ci_vacuna("pfizer", y="sin_otra_explicacion")[3], ")")),
                      cansino=c(str_c(ci_vacuna("cansino", y="todos")[1], " (", ci_vacuna("cansino", y="todos")[2], "-", ci_vacuna("cansino", y="todos")[3], ")"), "0"),
                      sputnik=c(str_c(ci_vacuna("sputnik", y="todos")[1], " (", ci_vacuna("sputnik", y="todos")[2], "-", ci_vacuna("sputnik", y="todos")[3], ")"),
                                str_c(ci_vacuna("sputnik", y="sin_otra_explicacion")[1], " (", ci_vacuna("sputnik", y="sin_otra_explicacion")[2], "-", ci_vacuna("sputnik", y="sin_otra_explicacion")[3], ")")),
                      astra=c(str_c(ci_vacuna("astrazeneca", y="todos")[1], " (", ci_vacuna("astrazeneca", y="todos")[2], "-", ci_vacuna("astrazeneca", y="todos")[3], ")"),
                                str_c(ci_vacuna("astrazeneca", y="sin_otra_explicacion")[1], " (", ci_vacuna("astrazeneca", y="sin_otra_explicacion")[2], "-", ci_vacuna("astrazeneca", y="sin_otra_explicacion")[3], ")")),
                      sinovac=c(str_c(ci_vacuna("sinovac", y="todos")[1], " (", ci_vacuna("sinovac", y="todos")[2], "-", ci_vacuna("sinovac", y="todos")[3], ")"),
                                str_c(ci_vacuna("sinovac", y="sin_otra_explicacion")[1], " (", ci_vacuna("sinovac", y="sin_otra_explicacion")[2], "-", ci_vacuna("sinovac", y="sin_otra_explicacion")[3], ")"))
                      )
                      






```

